# MantisBT - GitHub Actions
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Linter

on:
  - push
  - pull_request

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          CSS_FILE_NAME: .stylelintrc.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Disable linters causing many errors we dont want to worry about for now
          VALIDATE_JSCPD: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
